name: Deploy Stack on aws 
on: 
  push: 
    branches:
      - main  # when ever any code to pushed to master branch it will trigger
    
jobs:  # we are creating jobs to perform steps
  deploy:
    runs-on: ubuntu-latest # from azure pool 
    
    steps: # steps to setup cdk and run cod
    - name: setup node.js 20 version
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: checkout git repo code to vm 
      uses: actions/checkout@v2 

    - name: verify code in vm 
      run: ls 